# cloudbuild.yaml
steps:
  # Step 1: Build Docker Image for Next.js app
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Next.js Image"
    args:
      - "build"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/${_AR_PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--build-arg"
      - "NEXT_PUBLIC_SOCKET_URL=${_NEXT_PUBLIC_SOCKET_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_FRONTEND_URL=${_NEXT_PUBLIC_FRONTEND_URL}"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  # Step 2: Push the built Docker Image to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Image"
    args:
      - "push"
      - "asia-southeast1-docker.pkg.dev/${_AR_PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"

  # Step 3: Deploy the Docker Image to Google Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy to Cloud Run"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "asia-southeast1-docker.pkg.dev/${_AR_PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--region"
      - "asia-southeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "3000"
      - "--set-env-vars"
      - "NEXT_PUBLIC_SOCKET_URL=${_NEXT_PUBLIC_SOCKET_URL},NEXT_PUBLIC_FRONTEND_URL=${_NEXT_PUBLIC_FRONTEND_URL},TZ=Asia/Bangkok"

# Images that will be pushed to Artifact Registry
images:
  - "asia-southeast1-docker.pkg.dev/${_AR_PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
