export enum SocketEnum {
  PATIENT_FORM_UPDATE = "PATIENT_FORM_UPDATE",
  TRIGGER_FORM_UPDATE = "TRIGGER_FORM_UPDATE",
  JOIN_FORM_ROOM = "JOIN_FORM_ROOM",
  MANAGE_FORMS = "MANAGE_FORMS",
  CLEAR_FORM_DATA = "CLEAR_FORM_DATA",
}
